#include "psalms.h"

const char *psalms[150] = {
    // Psalm 1
    "[1] That man hath perfect blessedness,\nwho walketh not astray\nIn "
    "counsel of ungodly men,\nnor stands in sinners’ way,\n\nNor sitteth "
    "in the scorner’s chair:\n[2] But placeth his delight\nUpon God’s law, "
    "and meditates\non his law day and night.\n\n[3] He shall be like a "
    "tree that grows\nnear planted by a river,\nWhich in his season yields "
    "his fruit,\nand his leaf fadeth never:\n\nAnd all he doth shall "
    "prosper well\n[4] The wicked are not so;\nBut like they are unto the "
    "chaff,\nwhich wind drives to and fro.\n\n[5] In judgment therefore "
    "shall not stand\nsuch as ungodly are;\nNor in th’ assembly of the "
    "just\nshall wicked men appear.\n\n[6] For why? the way of godly "
    "men\nunto the Lord is known:\nWhereas the way of wicked men\nshall "
    "quite be overthrown.",
    // Psalm 2
    "[1] Why rage the heathen? and vain things\nwhy do the people "
    "mind?\n[2] Kings of the earth do set themselves,\nand princes are "
    "combin’d,\n\nTo plot against the Lord, and his\nAnointed, saying "
    "thus,\n[3] Let us asunder break their bands,\nand cast their cords "
    "from us.\n\n[4] He that in heaven sits shall laugh;\nthe Lord shall "
    "scorn them all.\n[5] Then shall he speak to them in wrath,\nin rage "
    "he vex them shall.\n\n[6] Yet, notwithstanding, I have him\nto be my "
    "King appointed;\nAnd over Sion, my holy hill,\nI have him King "
    "anointed.\n\n[7] The sure decree I will declare:\nThe Lord hath said "
    "to me,\nThou art mine only Son; this day\nI have begotten "
    "thee.\n\n[8] Ask of me, and for heritage\nthe heathen I’ll make "
    "thine;\nAnd, for possession, I to thee\nwill give earth’s utmost "
    "line.\n\n[9] Thou shalt, as with a weighty rod\nof iron, break them "
    "all;\nAnd, as a potter’s sherd, thou shalt\nthem dash in pieces "
    "small.\n\n[10] Now therefore, kings, be wise; be taught,\nye judges "
    "of the earth:\n[11] Serve God in fear, and see that ye\njoin "
    "trembling with your mirth.\n\n[12] Kiss ye the Son, lest in his "
    "ire\nye perish from the way,\nIf once his wrath begin to "
    "burn:\nbless’d all that on him stay.",
    // Psalm 3
    "[1] O Lord, how are my foes increas’d?\nagainst me many rise.\n[2] "
    "Many say of my soul, For him\nin God no succour lies.\n\n[3] Yet thou "
    "my shield and glory art,\nth’ uplifter of mine head.\n[4] I cry’d, "
    "and, from his holy hill,\nthe Lord me answer made.\n\n[5] I laid me "
    "down and slept; I wak’d;\nfor God sustained me.\n[6] I will not fear "
    "though thousands ten\nset round against me be.\n\n[7] Arise, O Lord; "
    "save me, my God;\nfor thou my foes hast stroke\nAll on the "
    "cheek-bone, and the teeth\nof wicked men hast broke.\n\n[8] Salvation "
    "doth appertain\nunto the Lord alone:\nThy blessing, Lord, for "
    "evermore\nthy people is upon.",
    // Psalm 4
    "[1] Give ear unto me when I call,\nGod of my righteousness:\nHave "
    "mercy, hear my pray’r; thou hast\nenlarg’d me in distress.\n\n[2] O "
    "ye the sons of men! how long\nwill ye love vanities?\nHow long my "
    "glory turn to shame,\nand will ye follow lies?\n\n[3] But know, that "
    "for himself the Lord\nthe godly man doth chuse:\nThe Lord, when I on "
    "him do call,\nto hear will not refuse.\n\n[4] Fear, and sin not; talk "
    "with your heart\non bed, and silent be.\n[5] Off ‘rings present of "
    "righteousness,\nand in the Lord trust ye.\n\n[6] O who will shew us "
    "any good?\nis that which many say:\nBut of thy countenance the "
    "light,\nLord, lift on us alway.\n\n[7] Upon my heart, bestow’d by "
    "thee,\nmore gladness I have found\nThan they, ev’n then, when corn "
    "and wine\ndid most with them abound.\n\n[8] I will both lay me down "
    "in peace,\nand quiet sleep will take;\nBecause thou only me to "
    "dwell\nin safety, Lord, dost make.",
    // Psalm 5
    "[1] Give ear unto my words, O Lord,\nmy meditation weigh.\n[2] Hear "
    "my loud cry, my King, my God;\nfor I to thee will pray.\n\n[3] Lord, "
    "thou shalt early hear my voice:\nI early will direct\nMy pray’r to "
    "thee; and, looking up,\nan answer will expect.\n\n[4] For thou art "
    "not a God that doth\nin wickedness delight;\nNeither shall evil dwell "
    "with thee,\n[5] Nor fools stand in thy sight.\n\nAll that ill-doers "
    "are thou hat’st;\n[6] Cutt’st off that liars be:\nThe bloody and "
    "deceitful man\nabhorred is by thee.\n\n[7] But I into thy house will "
    "come\nin thine abundant grace;\nAnd I will worship in thy "
    "fear\ntoward thy holy place.\n\n[8] Because of those mine "
    "enemies,\nLord, in thy righteousness\nDo thou me lead; do thou thy "
    "way\nmake straight before my face.\n\n[9] For in their mouth there is "
    "no truth,\ntheir inward part is ill;\nTheir throat’s an open "
    "sepulchre,\ntheir tongue doth flatter still.\n\n[10] O God, destroy "
    "them; let them be\nby their own counsel quell’d:\nThem for their many "
    "sins cast out,\nfor they ‘gainst thee rebell’d.\n\n[11] But let all "
    "joy that trust in thee,\nand still make shouting noise;\nFor them "
    "thou sav’st; let all that love\nthy name in thee rejoice.\n[12] For, "
    "Lord, unto the righteous man\nthou wilt thy blessing yield:\nWith "
    "favour thou wilt compass him\nabout, as with a shield.",
    // Psalm 6
    "[1] Lord, in thy wrath rebuke me not;\nNor in thy hot rage chasten "
    "me.\n[2] Lord, pity me, for I am weak:\nHeal me, for my bones vexed "
    "be.\n\n[3] My soul is also vexed sore;\nBut, Lord, how long stay wilt "
    "thou make?\n[4] Return, O Lord, my soul set free;\nO save me, for thy "
    "mercies’ sake.\n\n[5] Because those that deceased are\nOf thee shall "
    "no "
    "remembrance have;\nAnd who is he that will to thee\nGive praises "
    "lying "
    "in the grave?\n\n[6] I with my groaning weary am,\nI also all the "
    "night "
    "my bed\nHave caused for to swim; and I\nWith tears my couch have "
    "watered.\n\n[7] Mine eye, consum’d with grief, grows old,\nBecause of "
    "all mine enemies.\n[8] Hence from me, wicked workers all;\nFor God "
    "hath "
    "heard my weeping cries.\n\n[9] God hath my supplication heard,\nMy "
    "pray’r received graciously\n[10] Sham’d and sore vex’d be all my "
    "foes,\nSham’d and back turned suddenly.\n\nSecond Version "
    "(C.M.)\n\n[1] "
    "In thy great indignation,\nO Lord, rebuke me not;\nNor on me lay thy "
    "chast ‘ning hand,\nin thy displeasure hot.\n\n[2] Lord, I am weak, "
    "therefore on me\nhave mercy, and me spare:\nHeal me, O Lord, because "
    "thou know’st\nmy bones much vexed are.\n\n[3] My soul is vexed sore: "
    "but, Lord,\nhow long stay wilt thou make?\n[4] Return, Lord, free my "
    "soul; and save\nme, for thy mercies’ sake.\n\n[5] Because of thee in "
    "death there shall\nno more remembrance be:\nOf those that in the "
    "grave "
    "do lie,\nwho shall give thanks to thee?\n\n[6] I with my groaning "
    "weary "
    "am,\nand all the night my bed\nI caused for to swim; with tears\nmy "
    "couch I watered.\n\n[7] By reason of my vexing grief,\nmine eye "
    "consumed "
    "is;\nIt waxeth old, because of all\nthat be mine enemies.\n\n[8] But "
    "now, depart from me all ye\nthat work iniquity:\nFor why? the Lord "
    "hath "
    "heard my voice,\nwhen I did mourn and cry.\n\n[9] Unto my "
    "supplication\nthe Lord did hearing give:\nWhen I to him my prayer "
    "make,\nthe Lord will it receive.\n\n[10] Let all be sham’d and "
    "troubled "
    "sore,\nThat en’mies are to me;\nLet them turn back, and "
    "suddenly\nashamed let them be.",
    // Psalm 7
    "[1] O Lord my God, in thee do I\nmy confidence repose:\nSave and "
    "deliver me from all\nmy persecuting foes;\n\n[2] Lest that the enemy "
    "my soul\nshould, like a lion, tear,\nIn pieces rending it, while "
    "there\nis no deliverer.\n\n[3] O Lord my God, if it be so\nthat I "
    "committed this;\nIf it be so that in my hands\niniquity there "
    "is:\n\n[4] If I rewarded ill to him\nthat was at peace with "
    "me;\n(Yea, ev’n the man that without cause\nmy foe was I did "
    "free;)\n\n[5] Then let the foe pursue and take\nmy soul, and my life "
    "thrust\nDown to the earth, and let him lay\nmine honour in the "
    "dust.\n\n[6] Rise in thy wrath, Lord, raise thyself,\nfor my foes "
    "raging be;\nAnd, to the judgment which thou hast\ncommanded, wake for "
    "me.\n\n[7] So shall th’ assembly of thy folk\nabout encompass "
    "thee:\nThou, therefore, for their sakes, return\nunto thy place on "
    "high.\n\n[8] The Lord he shall the people judge:\nmy judge, Jehovah, "
    "be,\nAfter my righteousness, and mine\nintegrity in me.\n\n[9] O let "
    "the wicked’s malice end;\nbut stablish stedfastly\nThe righteous: for "
    "the righteous God\nthe hearts and reins doth try.\n\n[10] In God, who "
    "saves th’ upright in heart,\nis my defence and stay.\n[11] God just "
    "men judgeth, God is wroth\nwith ill men ev’ry day.\n\n[12] If he do "
    "not return again,\nthen he his sword will whet;\nHis bow he hath "
    "already bent,\nand hath it ready set:\n\n[13] He also hath for him "
    "prepar’d\nthe instruments of death;\nAgainst the persecutors he\nhis "
    "shafts ordained hath.\n\n[14] Behold, he with iniquity\ndoth travail, "
    "as in birth;\nA mischief he conceived hath,\nand falsehood shall "
    "bring forth.\n\n[15] He made a pit and digg’d it deep,\nanother there "
    "to take;\nBut he is fall’n into the ditch\nwhich he himself did "
    "make.\n\n[16] Upon his own head his mischief\nshall be returned "
    "home;\nHis vi’lent dealing also down\non his own pate shall "
    "come.\n\n[17] According to his righteousness\nthe Lord I’ll "
    "magnify;\nAnd will sing praise unto the name\nof God that is most "
    "high.",
    // Psalm 8
    "[1] How excellent in all the earth,\nLord, our Lord, is thy "
    "name!\nWho hast thy glory far advanc’d\nabove the starry "
    "frame.\n\n[2] From infants’ and from sucklings’ mouth\nthou didest "
    "strength ordain,\nFor thy foes’ cause, that so thou might’st\nth’ "
    "avenging foe restrain.\n\n[3] When I look up unto the heav’ns,\nwhich "
    "thine own fingers fram’d,\nUnto the moon, and to the stars,\nwhich "
    "were by thee ordain’d;\n\n[4] Then say I, What is man, that "
    "he\nremember’d is by thee?\nOr what the son of man, that thou\nso "
    "kind to him should’st be?\n\n[5] For thou a little lower hast\nhim "
    "than the angels made;\nWith glory and with dignity\nthou crowned hast "
    "his head.\n\n[6] Of thy hands’ works thou mad’st him lord,\nall "
    "under’s feet didst lay;\n[7] All sheep and oxen, yea, and "
    "beasts\nthat in the field do stray;\n\n[8] Fowls of the air, fish of "
    "the sea,\nall that pass through the same.\n[9] How excellent in all "
    "the earth,\nLord, our Lord, is thy name!",
    // Psalm 9
    "[1] Lord, thee I’ll praise with all my heart,\nthy wonders all "
    "proclaim.\n[2] In thee, most High, I’ll greatly joy,\nand sing unto "
    "thy name.\n\n[3] When back my foes were turn’d, they fell,\nand "
    "perish’d at thy sight:\n[4] For thou maintain’dst my right and "
    "cause;\non throne sat’st judging right.\n\n[5] The heathen thou "
    "rebuked hast,\nthe wicked overthrown;\nThou hast put out their names, "
    "that they\nmay never more be known.\n\n[6] O en’my! now destructions "
    "have\nan end perpetual:\nThou cities raz’d; perish’d with them\nis "
    "their memorial.\n\n[7] God shall endure for aye; he doth\nfor "
    "judgment set his throne;\n[8] In righteousness to judge the "
    "world,\njustice to give each one.\n\n[9] God also will a refuge "
    "be\nfor those that are oppress’d;\nA refuge will he be in times\nof "
    "trouble to distress’d.\n\n[10] And they that know thy name, in "
    "thee\ntheir confidence will place:\nFor thou hast not forsaken "
    "them\nthat truly seek thy face.\n\n[11] O sing ye praises to the "
    "Lord,\nthat dwells in Sion hill;\nAnd all the nations among\nhis "
    "deeds record ye still.\n\n[12] When he enquireth after blood,\nhe "
    "then rememb’reth them:\nThe humble folk he not forgets\nthat call "
    "upon his name.\n\n[13] Lord, pity me; behold the grief\nwhich I from "
    "foes sustain;\nEv’n thou, who from the gates of death\ndost raise me "
    "up again;\n\n[14] That I, in Sion’s daughters’ gates,\nmay all thy "
    "praise advance;\nAnd that I may rejoice always\nin thy "
    "deliverance.\n\n[15] The heathen are sunk in the pit\nwhich they "
    "themselves prepar’d;\nAnd in the net which they have hid\ntheir own "
    "feet fast are snar’d.\n\n[16] The Lord is by the judgment "
    "known\nwhich he himself hath wrought:\nThe sinners’ hands do make the "
    "snares\nwherewith themselves are caught.\n\n[17] They who are wicked "
    "into hell\neach one shall turned be;\nAnd all the nations that "
    "forget\nto seek the Lord most high.\n\n[18] For they that needy are "
    "shall not\nforgotten be alway;\nThe expectation of the poor\nshall "
    "not be lost for aye.\n\n[19] Arise, Lord, let not man prevail;\njudge "
    "heathen in thy sight:\n[20] That they may know themselves but "
    "men,\nthe nations, Lord, affright.",
    // Psalm 10
    "[1] Wherefore is it that thou, O Lord,\ndost stand from us afar?\nAnd "
    "wherefore hidest thou thyself,\nwhen times so troublous are?\n\n[2] "
    "The wicked in his loftiness\ndoth persecute the poor:\nIn these "
    "devices they have fram’d\nlet them be taken sure.\n\n[3] The wicked "
    "of his heart’s desire\ndoth talk with boasting great;\nHe blesseth "
    "him that’s covetous,\nwhom yet the Lord doth hate.\n\n[4] The wicked, "
    "through his pride of face,\non God he doth not call;\nAnd in the "
    "counsels of his heart\nthe Lord is not at all.\n\n[5] His ways they "
    "always grievous are;\nthy judgments from his sight\nRemoved are: at "
    "all his foes\nhe puffeth with despight.\n\n[6] Within his heart he "
    "thus hath said,\nI shall not moved be;\nAnd no adversity at "
    "all\nshall ever come to me.\n\n[7] His mouth with cursing, fraud, "
    "deceit,\nis fill’d abundantly;\nAnd underneath his tongue there "
    "is\nmischief and vanity.\n\n[8] He closely sits in villages;\nhe "
    "slays the innocent:\nAgainst the poor that pass him by\nhis cruel "
    "eyes are bent.\n\n[9] He, lion-like, lurks in his den;\nhe waits the "
    "poor to take;\nAnd when he draws him in his net,\nhis prey he doth "
    "him make.\n\n[10] Himself he humbleth very low,\nhe croucheth down "
    "withal,\nThat so a multitude of poor\nmay by his strong ones "
    "fall.\n\n[11] He thus hath said within his heart,\nThe Lord hath "
    "quite forgot;\nHe hides his countenance, and he\nfor ever sees it "
    "not.\n\n[12] O Lord, do thou arise; O God,\nlift up thine hand on "
    "high:\nPut not the meek afflicted ones\nout of thy memory.\n\n[13] "
    "Why is it that the wicked man\nthus doth the Lord despise?\nBecause "
    "that God will it require\nhe in his heart denies.\n\n[14] Thou hast "
    "it seen; for their mischief\nand spite thou wilt repay:\nThe poor "
    "commits himself to thee;\nthou art the orphan’s stay.\n\n[15] The arm "
    "break of the wicked man,\nand of the evil one;\nDo thou seek out his "
    "wickedness,\nuntil thou findest none.\n\n[16] The Lord is King "
    "through ages all,\nev’n to eternity;\nThe heathen people from his "
    "land\nare perish’d utterly.\n\n[17] O Lord, of those that humble "
    "are\nthou the desire didst hear;\nThou wilt prepare their heart, and "
    "thou\nto hear wilt bend thine ear;\n\n[18] To judge the fatherless, "
    "and those\nthat are oppressed sore;\nThat man, that is but sprung of "
    "earth,\nmay them oppress no more.",
};
